POST http://localhost:3003/api/users
Content-Type: application/json

{
	"username": "mallikasmikko",
  	"name": "Mikko Mallikas",
  	"password": "salasana1"
}

{
	"username": "exampleEzzi",
  	"name": "Essi Esimerkki",
  	"password": "secret2"
}

{
	"username": "teTe",
  	"name": "Tero Testaaja",
  	"password": "test3"
}


