POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImV4YW1wbGVFenppIiwiaWQiOiI2MDU4NGYzNGU3NTc3Yzg0OGFiZTM5OGQiLCJpYXQiOjE2MTY0MDA0MDl9.wWrAjwzBbzTBXpuXS8tigscL7KYAVIu9x87Hc_8mBgc'

{
	"title": "Uusi Muusa",
  	"author": "Eeva Kolu",
  	"url": "https://www.uusimuusa.fi/",
  	"likes": 7
}