name: Bloglist app pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: npm install backend 
        run: npm install
      - name: npm install frontend
        run: cd bloglist-frontend/ && npm install
      - name: lint
        run: npm run lint && cd bloglist-frontend/ && npm run lint
      - name: create .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_MONGODB_URI: ${{ secrets.MONGODB_URI }}
          envkey_TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          envkey_SECRET: ${{ secrets.SECRET }}
          envkey_PORT: ${{ secrets.PORT }}
      - name: unit test frontend
        run: cd bloglist-frontend/ && CI=true npm test
      - name: unit test backend
        run: npm run test
      - name: e2e testing
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: | 
            npm run start:test
            cd bloglist-frontend/ && npm start
          wait-on: http://localhost:3000